import type { NextApiRequest, NextApiResponse } from "next";
import jwt from "jsonwebtoken";
// this is automatically generated by prisma
// @ts-expect-error
import schema from "@jjordy/data/json-schema.json";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const { cookies } = req;
  const { JWT_SECRET } = process.env;
  if (
    cookies["token"] &&
    JWT_SECRET &&
    jwt.verify(cookies["token"], JWT_SECRET)
  ) {
    const { id, created_at, updated_at, author, comments, ...updatable } =
      schema.definitions.Ticket.properties;
    return res.status(200).json({
      $schema: schema.$schema,
      properties: updatable,
      definitions: schema.definitions,
    });
  }
  return res.status(401).end();
}
