import type { NextApiRequest, NextApiResponse } from "next";
// this is automatically generated by prisma
// @ts-expect-error
import schema from "@jjordy/data/json-schema.json";
import { useApiRequestHandler } from "@/lib/api";

async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { salt, hash, id, ...updatable } = schema.definitions.User.properties;
  return res.status(200).json({
    $schema: schema.$schema,
    properties: updatable,
    definitions: schema.definitions,
  });
}

export default useApiRequestHandler({
  GET: handler,
});
